name: flutter_movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  http: ^1.5.0
  font_awesome_flutter: ^10.10.0
  youtube_player_flutter: ^9.1.3
  webview_flutter: ^4.13.0
  fluttertoast: ^9.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.2
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  package_info_plus: ^8.1.2
  provider: ^6.1.2
  share_plus: ^10.1.3
  responsive_navigation_bar: ^5.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/Flick.jpg
    - assets/images/Flick_NoInfo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Flick.jpg"
  adaptive_icon_background: "#0A1929"
  adaptive_icon_foreground: "assets/images/Flick.jpg"
