// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyG0GP6_udiekkSrgf0v5NQNUGKcIE3Uw',
    appId: '1:1049565528209:web:dcced40d9be62b8916ff30',
    messagingSenderId: '1049565528209',
    projectId: 'flutter-movie-app-253e7',
    authDomain: 'flutter-movie-app-253e7.firebaseapp.com',
    storageBucket: 'flutter-movie-app-253e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHf1C-MYTAAUrRBd6XdLrX5FkcvyXSpG4',
    appId: '1:1049565528209:android:aed4d926cf6e885816ff30',
    messagingSenderId: '1049565528209',
    projectId: 'flutter-movie-app-253e7',
    storageBucket: 'flutter-movie-app-253e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCi1_ICY-Fxp46LAZlU__6y6L-8tl8B4s',
    appId: '1:1049565528209:ios:0801d48d19f374e716ff30',
    messagingSenderId: '1049565528209',
    projectId: 'flutter-movie-app-253e7',
    storageBucket: 'flutter-movie-app-253e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCi1_ICY-Fxp46LAZlU__6y6L-8tl8B4s',
    appId: '1:1049565528209:ios:0801d48d19f374e716ff30',
    messagingSenderId: '1049565528209',
    projectId: 'flutter-movie-app-253e7',
    storageBucket: 'flutter-movie-app-253e7.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyG0GP6_udiekkSrgf0v5NQNUGKcIE3Uw',
    appId: '1:1049565528209:web:5145b461a93f7b2616ff30',
    messagingSenderId: '1049565528209',
    projectId: 'flutter-movie-app-253e7',
    authDomain: 'flutter-movie-app-253e7.firebaseapp.com',
    storageBucket: 'flutter-movie-app-253e7.firebasestorage.app',
  );
}
